name: novel to kindle

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements.txt
      - run: python main.py
      - if: git diff --name-only | grep novel_list.json >/dev/null
        run: |
          chmod +x kindlegen
          ./kindlegen -unicode content.opf
      - if: git diff --name-only | grep novel_list.json >/dev/null
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Convert
          to: ${{secrets.KINDLE_EMAIL}}
          from: novel2kindle <${{secrets.MAIL_USERNAME}}>
          secure: true
          body: "Job of ${{github.repository}} completed successfully!"
          attachments: content.mobi
      - if: git diff --name-only | grep novel_list.json >/dev/null
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add novel_list.json
          git commit -m "update article_list"
          git push
